name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: 3.1.101
      - name: Run Test
        run: dotnet test ./SlackCoffee.sln -c Release
